from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19687432ecc6'
down_revision = 'c6506201bb71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('details', sa.String(length=200), nullable=True))  # Specify length for VARCHAR
    
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=200), nullable=True))  # Specify length for VARCHAR

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    with op.batch_alter_table('billing_reports', schema=None) as batch_op:
        batch_op.drop_column('details')

    # ### end Alembic commands ###
