"""Remove default value for role column in User model

Revision ID: 7bed25509f7f
Revises: 
Create Date: 2024-11-06 19:45:06.553186

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7bed25509f7f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('farmer', 'customer', 'admin', name='user_roles'),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('farmer', 'customer', 'admin', name='user_roles'),
               type_=mysql.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
